[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 100
startCommand = "uvicorn runthroughlinehackathor.main:app --host 0.0.0.0 --port $PORT"
